// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-p2Vk8FB8TscBLHMf3PNzJnPumpJlMU8',
    appId: '1:1096783478376:web:5c35596a06755f4dbe45dd',
    messagingSenderId: '1096783478376',
    projectId: 'qzcards-49ee1',
    authDomain: 'qzcards-49ee1.firebaseapp.com',
    storageBucket: 'qzcards-49ee1.appspot.com',
    measurementId: 'G-48MWB1KTMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndsvw9rtW7gZw5-wGm-SsUUqSxh4t96Y',
    appId: '1:1096783478376:android:cc3e6e7986983294be45dd',
    messagingSenderId: '1096783478376',
    projectId: 'qzcards-49ee1',
    storageBucket: 'qzcards-49ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU8NJNKKBDbApBh36VaAjWn6KxRdQC3k',
    appId: '1:1096783478376:ios:0be624d4667b7c19be45dd',
    messagingSenderId: '1096783478376',
    projectId: 'qzcards-49ee1',
    storageBucket: 'qzcards-49ee1.appspot.com',
    iosClientId: '1096783478376-t64blj27ntc40jnugaa5au9uop65es6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeQuizme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANU8NJNKKBDbApBh36VaAjWn6KxRdQC3k',
    appId: '1:1096783478376:ios:0be624d4667b7c19be45dd',
    messagingSenderId: '1096783478376',
    projectId: 'qzcards-49ee1',
    storageBucket: 'qzcards-49ee1.appspot.com',
    iosClientId: '1096783478376-t64blj27ntc40jnugaa5au9uop65es6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeQuizme',
  );
}
